# General Settings
name: Arturo Moncada-Torres
job_title: Biomedical Data Scientist
email: arturomoncadatorres@gmail.com
description: Passionate about improving peopleâ€™s health through data-driven solutions. Nintendo and Marvel enthusiast.
avatar: /multimedia/avatar.jpeg
favicon: /favicon.ico
twitter_handler: amoncadatorres
analytics_code: UA-XXXXXXX-2
disqus: arturomoncadatorres

# Social Accounts
social_networks:
-  { name: facebook, url: '' }
-  { name: twitter, url: 'https://twitter.com/amoncadatorres' }
-  { name: instagram, url: '' }
-  { name: google-plus, url: '' }
-  { name: linkedin, url: 'https://www.linkedin.com/in/arturomoncadatorres/' }
-  { name: skype, url: '' }
-  { name: github, url: 'https://github.com/arturomoncadatorres' }
-  { name: google-scholar, url: 'https://scholar.google.com/citations?user=o0pPxc8AAAAJ&hl=en' }
-  { name: orcid, url: 'https://orcid.org/0000-0001-7233-2117' }
-  { name: codepen, url: '' }
-  { name: stack-overflow, url: '' }
-  { name: dribbble, url: '' }
-  { name: behance, url: '' }
-  { name: pinterest, url: '' }
-  { name: tumblr, url: '' }
# -  { name: youtube, url: 'https://www.youtube.com/channel/UCMORmWOBKewmqVYI3PZFABQ?feature=mhee' }
-  { name: vimeo, url: '' }
-  { name: vine, url: '' }
-  { name: 500px, url: '' }
-  { name: flickr, url: '' }
-  { name: spotify, url: '' }
-  { name: steam, url: '' }
-  { name: wordpress, url: '' }
-  { name: xing, url: '' }
-  { name: bitcoin, url: '' }
-  { name: pocket, url: '' }
-  { name: applemusic, url: '' }


# Modules Settings
show_categories: 1
show_tags: 1
show_email: 1
show_rss: 0
show_comments: 1
show_menu: 1
fixed_sidebar: 1

# Defaults
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      comments: "true"

# Serving
url: "//arturomoncadatorres.com"
baseurl: ""

# Includes
include: ["_pages"]

# Excludes
exclude: ["instructions.md"]

# Outputting
permalink: /:categories/:title.html
category_dir: categories

# Pagination
paginate: 10
paginate_path: "/page:num/"

# Conversion
markdown: kramdown
excerpt_separator: <!--more-->

# Assets Settings
sass:
  sass_dir: assets/partials
  style: compressed
